version: "2"
services:
  plone:
    # image: eeacms/eea.docker.eionet:latest
    build: ../
    depends_on:
    - zeoserver
    environment:
    - ZEO_ADDRESS=zeoserver:8080
    volumes:
    - ../custom.cfg:/plone/instance/custom.cfg
    - ../src/:/plone/instance/src/
    ports:
    - 8080:8080
    # command: bash -c "tail -f /dev/null"

  zeoserver:
    image: plone/plone:5.1.5
    command: zeo
    volumes:
    - data:/data

volumes:
  data:
