version: "2"
services:
  haproxy:
    image: eeacms/haproxy
    ports:
    - 8080:5000
    - 1936:1936
    depends_on:
    - plone
    environment:
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"

  plone:
    # image: eeacms/eea.docker.eionet:latest
    build: ../
    depends_on:
    - zeoserver
    environment:
    - ZEO_ADDRESS=zeoserver:8080
    volumes:
    - ../site.cfg:/plone/instance/site.cfg
    - ../src:/plone/instance/src/
    command: bash -c "tail -f /dev/null"

  zeoserver:
    image: plone/plone:5.1.5
    command: zeo
    volumes:
    - data:/data

volumes:
  data:
